### ISSUE TITLE
Looks like you need to update your shell code(install.sh).

### ISSUE THREAD

**Issue by luckyboxx** [tarunkant/Gopherus#14]
Hi,👋👋
I'm student in Repulic of Korea.
I'm study about cyber security.

Thanks to the tool you made recently, I solved one CTF problem well.👍👍
But there are some problems with the shell code you made(a.k.a install.sh).
If you look at the picture below, you can see an error.

![1](https://user-images.githubusercontent.com/44025989/128259479-0c4edcea-800b-4f36-a76f-ee1d0f4e802c.png)

The server I am currently using is Ubuntu 20.04.
If you look at the picture below, pip2 is not supported in that environment.

![2](https://user-images.githubusercontent.com/44025989/128259491-39a47075-b23e-4d25-ac9b-f2ec78d1db0e.png)

Operating systems and tools are updated every year.
Accordingly, it seems that the code needs to be modified.

e.g.)
![3](https://user-images.githubusercontent.com/44025989/128259754-5a809869-cf05-47ea-ace5-e69f69eda128.JPG)

**Comment by tarunkant** [comment]
Hello @luckyboxx,

Thanks! 
Actually the tool works in python2 only as of now, I need to update the tool for python3, that I will do surely as soon as I get some time from my regular work.

Thanks,

**Comment by honphilemon** [comment]
Please do , is needed for ssrf testing.

**Comment by tarunkant** [comment]
Hello @honphilemon,
Until then you can use this for installation:

Install python2 pip via:
```
wget https://bootstrap.pypa.io/pip/2.7/get-pip.py; python2 get-pip.py
```

Then run the following install.sh:
```
#!/bin/bash
python2 -m pip install argparse
python2 -m pip install requests
chmod +x gopherus.py
ln -sf $(pwd)/gopherus.py /usr/local/bin/gopherus
```

**Comment by tarunkant** [comment]
Updated the install.sh
