### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sajeeshab** [tarunkant/Gopherus#16]
File "/home/sajeesh/Gopherus/gopherus.py", line 28
    print colors.green + """
    ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by sajeeshab** [comment]
└─$ sudo bash install.sh
/usr/bin/python2: No module named pip
/usr/bin/python2: No module named pip

**Comment by tarunkant** [comment]
@Sajeeshab, Please install `pip`.
`wget https://bootstrap.pypa.io/pip/2.7/get-pip.py` 
`python2 get-pip.py`
