### ISSUE TITLE
Redis attack incorrect

### ISSUE THREAD

**Issue by dinhbaouit** [tarunkant/Gopherus#4]
please replace
"\\r\n    "  to "\\r\\n"
If need, got that https://pastebin.com/raw/Va3CH3tK

**Comment by dinhbaouit** [comment]
update: https://pastebin.com/raw/sYNYGPmf

**Comment by tarunkant** [comment]
Hey, I don't think it would be a problem, but the previous script still working right?

**Comment by tarunkant** [comment]
Thanks for your contribution.
At the time of putting these in a function, I made indentation correct using tab(my bad), which made the file not working.
